spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/atithih_db
    username: postgres
    password: Password@123

  jpa:
    show_sql: true

    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect